#ifndef KATE_CONFIG_H
#define KATE_CONFIG_H

/* config.h. Generated by cmake from config.h.cmake */

static const int KateVersionMajor = 5;
static const int KateVersionMinor = 0;
static const int KateVersionMicro = 0;

static const float KateVersion = 5.0;

#define KATE_VERSION "5.0.0"

#cmakedefine HAVE_FDATASYNC 1
#cmakedefine HAVE_CTERMID 1

#endif
