#ifndef KATE_BUILD_CONFIG_H
#define KATE_BUILD_CONFIG_H

/* config.h. Generated by cmake from config.h.cmake */

#cmakedefine01 EDITORCONFIG_FOUND
#cmakedefine01 LIBGIT2_FOUND

#cmakedefine01 HAVE_FDATASYNC
#cmakedefine01 BUILD_VIMODE

#endif
